title: 笨方法学写作
description: "专注卡片创作、认知科学、刻意练习、写作技巧的博客"
author: cnfeat
language: zh-CN
url: "https://cnfeat.com"
baseurl: ""
description: "feedId:55130722692595719+userId:59030678518927360"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-80884545-1

footer: yes
footer_url: "http://www.HardWayLab.com"
footer_text: "笨方法实验室：世上无难事，只怕笨方法"

favicon: true
favicon_location: "images/favicon.png"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "关于"
    link: "/about"
  - name: "博客"
    link: "/blog"
  - name: "作品"
    link: "/books"
