title: 卡片创作实验室
description: "专注卡片创作、认知科学、刻意练习、写作技巧的博客"
author: cnfeat
language: zh-CN
url: "https://cnfeat.com"
baseurl: ""

timezone: Asia/Shanghai

markdown: kramdown
highlighter: rouge

permalink: /posts/:year/:month/:day/:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  
tracking_id: G-DG9PZJ46EB

# SEO
logo: /images/icon.png
twitter:
  username: cnfeat
  card: summary_large_image

social:
  name: cnfeat
  links:
    - https://github.com/cnfeat
    - https://www.yuque.com/hardwaylab

webmaster_verifications:
  google:
  baidu:
  bing:

# 默认 SEO 元信息
defaults:
  - scope:
      path: ""
    values:
      image: /images/icon.png
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: cnfeat
      image: /images/icon.png

# GitHub Pages 需要的配置
github:
  repository: cnfea/cnfeat.github.io

footer: yes
footer_url: "https://hardwaylab.com"
footer_text: "笨方法实验室：世上无难事，只怕笨方法"

favicon: true
favicon_location: "images/favicon.png"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "关于"
    link: "/about"
  - name: "博客"
    link: "/blog"
  - name: "作品"
    link: "/books"
